### ISSUE TITLE
[FEATURE] Transactional Zone Tree Iterator

### ISSUE THREAD

**Issue by nzdev** [koculu/ZoneTree#10]
**Is your feature request related to a problem? Please describe.**
ITransactionalZoneTree does not have a way to iterate the items.

**Describe the solution you'd like**
CreateIterator from IZoneTree supported on ITransactionalZoneTree.

**Describe alternatives you've considered**
I've considered using IZoneTree instead of ITransactionalZoneTree, however I require transaction support and it does not appear to be possible to have both IZoneTree and ITransactionalZoneTree in use at the same time.

**Additional context**

**Comment by koculu** [comment]
Additional notes:

ZoneTree supports only OptimisticTransactions right now.
My long-term goal is to add support for the following transaction types:
* Two-phase locking (2PL)
* Multiversion concurrency control (MVCC)

Starting reference on the topic: https://en.wikipedia.org/wiki/Concurrency_control

How Optimistic Concurrency works?
https://en.wikipedia.org/wiki/Timestamp-based_concurrency_control

Reading values transactionally comes with a cost:  every read creates a read-write stamp and adds a transaction dependency record if the read value is written by another uncommitted transaction.

If you don't want this cost and reading committed values is ok for your business logic,
you may use ReadCommittedTryGet instead of a TryGet in the iteration.
In this case, the isolation level would be ReadCommittedSnapshot.

If you directly use the non-transactional iterator's value, the isolation level becomes dirty reads.

In addition to avoid phantom reads in iterating scenario, Range locks should be implemented. It is not supported yet.
